import os

from dotenv import load_dotenv


################################################################################

# Loading environment configuration variables
load_dotenv(".config")

TOKEN = os.getenv("TOKEN")

# CHANNELS
CHANNEL_LA_CARTE_ID = int(os.getenv("CHANNEL_LA_CARTE_ID"))

# MESSAGES
MESSAGE_REGLES_ID = int(os.getenv("MESSAGE_REGLES_ID"))
MESSAGE_CHOOSE_THEMES_ID = int(os.getenv("MESSAGE_CHOOSE_THEMES_ID"))

# Categories
CAT_EXPOSITIONS_ID = int(os.getenv("CAT_EXPOSITIONS_ID"))
CAT_MAGAZINES_ID = int(os.getenv("CAT_MAGAZINES_ID"))
CAT_BIBLIOTHEQUE_ID = int(os.getenv("CAT_BIBLIOTHEQUE_ID"))

# Categories Studios
CAT_STUDIO_2D_ID = int(os.getenv("CAT_STUDIO_2D_ID"))
CAT_STUDIO_3D_ID = int(os.getenv("CAT_STUDIO_3D_ID"))
CAT_STUDIO_GAME_ID = int(os.getenv("CAT_STUDIO_GAME_ID"))
CAT_STUDIO_PHOTO_ID = int(os.getenv("CAT_STUDIO_PHOTO_ID"))
CAT_STUDIO_VIDEO_ID = int(os.getenv("CAT_STUDIO_VIDEO_ID"))
CAT_STUDIO_MUSIQUE_ID = int(os.getenv("CAT_STUDIO_MUSIQUE_ID"))
CAT_STUDIO_DIY_ID = int(os.getenv("CAT_STUDIO_DIY_ID"))
CAT_STUDIO_ECRITURE_ID = int(os.getenv("CAT_STUDIO_ECRITURE_ID"))

# ROLES
# Moderator
ROLE_OWNER_ID = int(os.getenv("ROLE_OWNER_ID"))
ROLE_BARTENDER_ID = int(os.getenv("ROLE_BARTENDER_ID"))
ROLE_BARTENDER_BOT_ID = int(os.getenv("ROLE_BARTENDER_BOT_ID"))

# Ranking
ROLE_CLIENT_DE_PASSAGE_ID = int(os.getenv("ROLE_CLIENT_DE_PASSAGE_ID"))
ROLE_ESPRESSO_ID = int(os.getenv("ROLE_ESPRESSO_ID"))
ROLE_DOUBLE_ESPRESSO_ID = int(os.getenv("ROLE_DOUBLE_ESPRESSO_ID"))
ROLE_AMERICANO_ID = int(os.getenv("ROLE_AMERICANO_ID"))
ROLE_CAPPUCCINO_ID = int(os.getenv("ROLE_CAPPUCCINO_ID"))
ROLE_MACHIATTO_ID = int(os.getenv("ROLE_MACHIATTO_ID"))
ROLE_MACHIATTO_LATTE_ID = int(os.getenv("ROLE_MACHIATTO_LATTE_ID"))
ROLE_IRISH_COFFEE_ID = int(os.getenv("ROLE_IRISH_COFFEE_ID"))

# Themes
ROLE_DESSINATEUR_ID = int(os.getenv("ROLE_DESSINATEUR_ID"))
ROLE_GRAPHISTE_3D_ID = int(os.getenv("ROLE_GRAPHISTE_3D_ID"))
ROLE_GAME_DESIGNER_ID = int(os.getenv("ROLE_GAME_DESIGNER_ID"))
ROLE_PHOTOGRAPHE_ID = int(os.getenv("ROLE_PHOTOGRAPHE_ID"))
ROLE_VIDEASTE_ID = int(os.getenv("ROLE_VIDEASTE_ID"))
ROLE_MUSICIEN_ID = int(os.getenv("ROLE_MUSICIEN_ID"))
ROLE_BRICOLEUR_ID = int(os.getenv("ROLE_BRICOLEUR_ID"))
ROLE_ECRIVAIN_ID = int(os.getenv("ROLE_ECRIVAIN_ID"))

ROLE_EVERYONE_ID = int(os.getenv("ROLE_EVERYONE_ID"))

# Globals

XP_EXPOSITIONS_MESSAGE = int(os.getenv("XP_EXPOSITIONS_MESSAGE"))
XP_MAGAZINE_MESSAGE = int(os.getenv("XP_MAGAZINE_MESSAGE"))
XP_BIBLIOTHEQUE_MESSAGE = int(os.getenv("XP_BIBLIOTHEQUE_MESSAGE"))
XP_STUDIO_MESSAGE = int(os.getenv("XP_STUDIO_MESSAGE"))
XP_REACTION = int(os.getenv("XP_REACTION"))

XP_DAY = int(os.getenv("XP_DAY"))

# Rang initial
XP_RANK_CLIENT_DE_PASSAGE = int(os.getenv("XP_RANK_CLIENT_DE_PASSAGE"))
XP_RANK_ESPRESSO = int(os.getenv("XP_RANK_ESPRESSO"))
XP_RANK_DOUBLE_ESPRESSO = int(os.getenv("XP_RANK_DOUBLE_ESPRESSO"))
XP_RANK_AMERICANO = int(os.getenv("XP_RANK_AMERICANO"))
XP_RANK_CAPPUCCINO = int(os.getenv("XP_RANK_CAPPUCCINO"))
XP_RANK_MACHIATTO = int(os.getenv("XP_RANK_MACHIATTO"))
XP_RANK_MACHIATTO_LATTE = int(os.getenv("XP_RANK_MACHIATTO_LATTE"))
XP_RANK_IRISH_COFFEE = int(os.getenv("XP_RANK_IRISH_COFFEE"))

################################################################################
# List

LIST_MESSAGE_REACTION_IDS = [
    MESSAGE_REGLES_ID,
    MESSAGE_CHOOSE_THEMES_ID
]

LIST_ROLE_MODERATOR_IDS = [
    ROLE_OWNER_ID,
    ROLE_BARTENDER_ID,
    ROLE_BARTENDER_BOT_ID
]

LIST_ROLE_CLIENTS_IDS = [
    ROLE_CLIENT_DE_PASSAGE_ID,
    ROLE_ESPRESSO_ID,
    ROLE_DOUBLE_ESPRESSO_ID,
    ROLE_AMERICANO_ID,
    ROLE_CAPPUCCINO_ID,
    ROLE_MACHIATTO_ID,
    ROLE_MACHIATTO_LATTE_ID,
    ROLE_IRISH_COFFEE_ID
]

LIST_ROLE_THEMES_IDS = [
    ROLE_DESSINATEUR_ID,
    ROLE_GRAPHISTE_3D_ID,
    ROLE_GAME_DESIGNER_ID,
    ROLE_PHOTOGRAPHE_ID,
    ROLE_VIDEASTE_ID,
    ROLE_MUSICIEN_ID,
    ROLE_BRICOLEUR_ID,
    ROLE_ECRIVAIN_ID
]

LIST_CAT_STUDIOS_IDS = [
    CAT_STUDIO_2D_ID,
    CAT_STUDIO_3D_ID,
    CAT_STUDIO_GAME_ID,
    CAT_STUDIO_PHOTO_ID,
    CAT_STUDIO_VIDEO_ID,
    CAT_STUDIO_MUSIQUE_ID,
    CAT_STUDIO_DIY_ID,
    CAT_STUDIO_ECRITURE_ID
]